### ISSUE TITLE
Clearer error message for inappropriate instrument input

### ISSUE THREAD

**Issue by ngreifer** [zackfisher/MIIVsem#1]
It would be nice if the error message when inputting an inappropriate argument to `instruments` was more informative, perhaps distinguishing between improper syntax vs. bad or non-instruments. Currently I get `Error in start.idx[i]:end.idx[i] : NA/NaN argument`. This is a great package :)

**Comment by zackfisher** [comment]
Added error handling if improper syntax is passed to ```instruments```. A detailed description of the ```instruments``` argument syntax can be found in the documentation for ```miive```.
