### ISSUE TITLE
Using `matInv()` in `est2SLSCoef()`

### ISSUE THREAD

**Issue by marklhc** [zackfisher/MIIVsem#3]
Hi Zack,

Thank you very much for building the `MIIVsem` package. It helps me greatly in learning how to apply MIIV. 

I currently have a small data set with binary items and want to run MIIV with the PIV estimator. However, I got an error regarding problem in computing the Cholesky decomposition of the submatrices of the polychoric correlation when running `est2SLSCoef()`, specifically this part:

```R
    if(eq$categorical){
      chol2inv(chol(
        poly.mat[
          eq[["MIIVs"]], eq[["MIIVs"]], drop = FALSE
        ]
      ))
    }
```

I saw that the package has a `matInv()` helper function which can use `solve()` to find matrix inverse when the Cholesky approach fails, but the helper function is not used currently in the package. I've tried using `solve()` and it works on my data set (with some warnings from `lavaan`). Would it be possible to update the package to use in `matInv()` in `est2SLSCoef()`?

Thank you again. 

Mark

**Comment by zackfisher** [comment]
Hi Mark,

Thanks for the suggestion. I can certainly make this change.  I'll plan to update Github later today but it might take a few days to show up on Cran.  Hope all is well.

Zack
