### ISSUE TITLE
Inquiry about new warning message coming up when running miiv() in R

### ISSUE THREAD

**Issue by mkshirley87** [zackfisher/MIIVsem#4]
Hello,

Today I'm running the same code, with the same data and model, as I did a few weeks ago:

miiv_model <- '
          body =~ organs + FM + SM
          brain =~ TIV + cbrum + cbellum
          body ~ ht
          brain ~ ht
          body ~ brain
          '
m_m <- miive(model = miiv_model, data = new_vars, sarg.adjust = "holm", 
                se = "boot", boot.ci = "perc", missing = "twostage")

but now I'm getting the following warning:

Warning message:
In if (trySolve(BetaNA)) { :
   the condition has length > 1 and only the first element will be used

whereas before I wasn't getting any warning messages. 

is it possible this is due to a misalignment between newer versions of R/RStudio and the MIIVsem package? I seem to be getting the same results with the Warning as I did previously, but I'd still prefer to understand what's going on! Thanks in advance for any advice on this. 

Meghan

**Comment by zackfisher** [comment]
Thanks for getting in touch Meghan! I haven't seen this before. Could you let me know which versions of R and MIIVsem you were using when you encountered the error?  With that information I can try identify what is going on.

**Comment by mkshirley87** [comment]
Hello! No problem. Version of MIIVsem is 0.5.5, version of R is 4.0.2, and
not sure if it's important, but RStudio version is 1.3.1093.

**Comment by mkshirley87** [comment]
Hello again. To give an update to my earlier message, I have a similar model to before, except now I'm setting boot.ci = "basic" and I've added overid.degree = 2:

miiv_model <- '
body =~ organs + FM + SM
brain =~ TIV + cbrum + cbellum
body ~ ht
brain ~ ht
body ~ brain
'
m_m <- miive(model = miiv_model, data = new_vars, sarg.adjust = "holm",
se = "boot", boot.ci = "basic", missing = "twostage", overid.degree = 2)

Now, in addition to the warning I wrote about in my first message, I am getting a second warning message that looks even more serious:

Warning messages:
1: In if (trySolve(BetaNA)) { :
  the condition has length > 1 and only the first element will be used
2: In lav_model_vcov(lavmodel = lavmodel, lavsamplestats = lavsamplestats,  :
  lavaan WARNING:
    The variance-covariance matrix of the estimated parameters (vcov)
    does not appear to be positive definite! The smallest eigenvalue
    (= -2.689404e-15) is smaller than zero. This may be a symptom that
    the model is not identified.


Normally I would just think there was some problem with my model. But once again, this is a situation where I ran the exact model yesterday, and only got warning number 1, and now today, I'm simply running it again and now getting warning number 2. And, like before, the warnings don't seem to mean anything for the actual results, which remain the same. 

Any advice you might have about the situation would be much appreciated! 
Meghan

**Comment by zackfisher** [comment]
Hi Meghan, this should be a quick fix but I am absolutely slammed until Friday.  Does it work if I get back to you by Saturday with a fix?

**Comment by mkshirley87** [comment]
Of course, no worries at all.

**Comment by zackfisher** [comment]
The bug generating the warning message for trySolve has been fixed in the Github version of the package. Unfortunately I can't replicate the second warning in a general data example. I'm happy to take a look at your specific model if you email me a reproducible example.

**Comment by zackfisher** [comment]
Also, the trySolve bug would not have impacted your results.

**Comment by mkshirley87** [comment]
No this is great, thanks so much!
