### ISSUE TITLE
How to get the model fit indices

### ISSUE THREAD

**Issue by JY-Fang** [zackfisher/MIIVsem#6]
Hi,
Using the MIIVsem package, I defined a model and cutomized instruments, 
but it seems that the output of  fit <- miive(model, data, instruments) can not provide model fit indices like chi-square and df.
I was wondering how to fix this?
Thanks for the help.

**Comment by zackfisher** [comment]
Are the equation-level Sargan Chi-square tests missing from the output?

**Comment by JY-Fang** [comment]
> Are the equation-level Sargan Chi-square tests missing from the output?

Actually, I ran into two kinds of conditions. 
(1) Model 1, I used multiple indicators to define latents x and y, and the miive output gave the Sargan Chi-square for each equation, but I was wondering if I could get the model-level fitting index like Test statistic, CFI and RMSEA.
(2) Model 2, I used single indicator to define latents, and the miive give a warning that "Insufficient MIIVs to estimate the etax2, etay2 equations." The miive output gave parameter estimates but  with no equation-level Sargan Chi-square. I am also confused about it.
Looking forward to get your relpy.

**Comment by zackfisher** [comment]
Got it. For (1) MIIVsem provides the equation level fit statistics, but not global fit statistics common to many system-wide estimators. For (2) it is likely the equation of interest is just-identified, which means there are not enough MIIVs to perform the equation-level overidentification test. Feel free to email me with a working example and I can provide you with some additional information.

**Comment by JY-Fang** [comment]
> Got it. For (1) MIIVsem provides the equation level fit statistics, but not global fit statistics common to many system-wide estimators. For (2) it is likely the equation of interest is just-identified, which means there are not enough MIIVs to perform the equation-level overidentification test. Feel free to email me with a working example and I can provide you with some additional information.

Thank you so much! I will send you the example by e-mail.
