### ISSUE TITLE
summary.miivs() and summary.miive()?

### ISSUE THREAD

**Issue by erigdon** [zackfisher/MIIVsem#8]
The documentation dated July 13, 2021, mentions these functions, but R says they cannot be found. summary() works well enough. Were these functions an old idea, since discarded?

> summary.miive(Rigmod.miiv)
Error in summary.miive(Rigmod.miiv) : 
  could not find function "summary.miive"

**Comment by zackfisher** [comment]
Hi Ed! It has been a while but I think this is just a naming convention for the S3 method. So 'summary' calls the corresponding function based on the class of the object it is operating on. If you use 'summary' on a 'miive' or 'miivs' object you'll get the appropriate summary function without needing to explicitly type what the object is.

**Comment by erigdon** [comment]
Ah! Thank you!
-Ed Rigdon

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
